import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";

const BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";

const STEALTH_ARGS = [
  "--disable-blink-features=AutomationControlled",
  "--disable-features=IsolateOrigins,site-per-process",
  "--no-sandbox",
  "--disable-setuid-sandbox",
  "--disable-infobars",
  "--disable-dev-shm-usage",
];

const VIEWPORTS = [
  { width: 1366, height: 768 },
  { width: 1440, height: 900 },
  { width: 1536, height: 864 },
  { width: 1280, height: 800 },
];

function randomViewport() {
  return VIEWPORTS[Math.floor(Math.random() * VIEWPORTS.length)];
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let playwrightModule: any = null;

async function getPlaywright() {
  if (playwrightModule) return playwrightModule;
  try {
    playwrightModule = await import("playwright");
    return playwrightModule;
  } catch {
    console.warn("Playwright not available - browser-based extraction disabled");
    return null;
  }
}

export async function listSubtitlesViaBrowser(
  url: string
): Promise<{
  ccSubtitles: SubtitleTrack[];
  autoTranslated: SubtitleTrack[];
  videoInfo: {
    title: string;
    author: string;
    duration?: number;
    thumbnail?: string;
  } | null;
}> {
  const pw = await getPlaywright();
  if (!pw) return { ccSubtitles: [], autoTranslated: [], videoInfo: null };

  let browser: any = null;

  try {
    const viewport = randomViewport();

    browser = await pw.chromium.launch({
      headless: true,
      args: STEALTH_ARGS,
    });

    const context = await browser.newContext({
      userAgent: BROWSER_UA,
      viewport,
      locale: "en-US",
      timezoneId: "America/New_York",
      geolocation: { latitude: 40.7128, longitude: -74.006 },
      permissions: [],
    });

    // Inject stealth scripts to hide automation markers
    await context.addInitScript(() => {
      Object.defineProperty(navigator, "webdriver", { get: () => false });
      // @ts-ignore
      window.chrome = { runtime: {} };
      // Overwrite plugins length
      Object.defineProperty(navigator, "plugins", {
        get: () => [1, 2, 3, 4, 5],
      });
      Object.defineProperty(navigator, "languages", {
        get: () => ["en-US", "en"],
      });
    });

    const page = await context.newPage();
    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 30000 });
    await page.waitForTimeout(4000);

    const ccSubtitles: SubtitleTrack[] = [];
    const autoTranslated: SubtitleTrack[] = [];
    let videoInfo = null;

    // Extract subtitle tracks from <track> elements
    const tracks: { lang: string; label: string; kind: string; src: string }[] =
      await page.evaluate(() => {
        const trackElements = document.querySelectorAll("video track, audio track");
        return Array.from(trackElements).map((t) => ({
          lang: t.getAttribute("srclang") || t.getAttribute("lang") || "",
          label: t.getAttribute("label") || "",
          kind: t.getAttribute("kind") || "subtitles",
          src: t.getAttribute("src") || "",
        }));
      });

    for (const track of tracks) {
      const subTrack: SubtitleTrack = {
        langCode: track.lang,
        langName: track.label || track.lang,
        url: track.src,
        isAutoGenerated: track.kind === "captions",
        isTranslation: false,
      };

      if (track.kind === "subtitles") {
        ccSubtitles.push(subTrack);
      } else if (track.kind === "captions") {
        autoTranslated.push(subTrack);
      }
    }

    // Try to get video metadata
    try {
      videoInfo = await page.evaluate(() => {
        const title =
          (document.querySelector("h1")?.textContent || "").trim() ||
          (
            document.querySelector(
              'meta[property="og:title"]'
            ) as HTMLMetaElement
          )?.content ||
          document.title;
        const author =
          (
            document.querySelector(
              'meta[name="author"]'
            ) as HTMLMetaElement
          )?.content || "";
        const thumbnail =
          (
            document.querySelector(
              'meta[property="og:image"]'
            ) as HTMLMetaElement
          )?.content || "";
        return { title, author, thumbnail };
      });
    } catch {
      // ignore
    }

    await context.close();
    await browser.close();

    return { ccSubtitles, autoTranslated, videoInfo };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("Browser extraction error:", errorMsg);
    if (browser) {
      try {
        await browser.close();
      } catch {
        /* ignore */
      }
    }
    return { ccSubtitles: [], autoTranslated: [], videoInfo: null };
  }
}

export async function downloadSubtitleViaBrowser(
  url: string,
  langCode: string,
  _targetFormat: SubtitleFormat
): Promise<string | null> {
  const pw = await getPlaywright();
  if (!pw) return null;

  let browser: any = null;

  try {
    const viewport = randomViewport();

    browser = await pw.chromium.launch({
      headless: true,
      args: STEALTH_ARGS,
    });

    const context = await browser.newContext({
      userAgent: BROWSER_UA,
      viewport,
      locale: "en-US",
    });

    // Inject stealth scripts
    await context.addInitScript(() => {
      Object.defineProperty(navigator, "webdriver", { get: () => false });
      // @ts-ignore
      window.chrome = { runtime: {} };
      Object.defineProperty(navigator, "plugins", {
        get: () => [1, 2, 3, 4, 5],
      });
      Object.defineProperty(navigator, "languages", {
        get: () => ["en-US", "en"],
      });
    });

    const page = await context.newPage();

    let subtitleContent: string | null = null;

    page.on("response", async (response: any) => {
      const ct = response.headers()["content-type"] || "";
      const responseUrl = response.url();
      if (
        !subtitleContent &&
        (responseUrl.includes(langCode) ||
          responseUrl.includes("subtitle") ||
          responseUrl.includes("caption") ||
          responseUrl.includes("timedtext")) &&
        (ct.includes("text") || ct.includes("xml") || ct.includes("json"))
      ) {
        try {
          subtitleContent = await response.text();
        } catch {
          /* ignore */
        }
      }
    });

    await page.goto(url, { waitUntil: "domcontentloaded", timeout: 30000 });
    await page.waitForTimeout(6000);

    await context.close();
    await browser.close();

    return subtitleContent;
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("Browser download error:", errorMsg);
    if (browser) {
      try {
        await browser.close();
      } catch {
        /* ignore */
      }
    }
    return null;
  }
}
