import { getCookies } from "@/lib/anti-limit/cookie-manager";
import fs from "fs/promises";
import path from "path";
import os from "os";

/**
 * Write cookies from the database to a temporary Netscape-format file
 * that yt-dlp can consume via --cookies.
 *
 * Netscape format:
 *   domain  flag  path  secure  expiration  name  value
 */
export async function createTempCookieFile(
  platform: string
): Promise<string | null> {
  const raw = await getCookies(platform);
  if (!raw) return null;

  const tmpDir = path.join(os.tmpdir(), "mlangsub-cookies");
  await fs.mkdir(tmpDir, { recursive: true });

  const filePath = path.join(tmpDir, `${platform}-${Date.now()}.txt`);

  // If the cookies are already in Netscape format, write directly
  if (raw.includes("\t")) {
    await fs.writeFile(filePath, raw, "utf-8");
    return filePath;
  }

  // Otherwise, write a header and the raw cookie string
  const netscapeHeader = "# Netscape HTTP Cookie File\n# Generated by mLangSub\n\n";
  await fs.writeFile(filePath, netscapeHeader + raw, "utf-8");
  return filePath;
}

export async function cleanupTempCookieFile(
  filePath: string
): Promise<void> {
  try {
    await fs.unlink(filePath);
  } catch {
    // Best-effort cleanup
  }
}
