import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";
import { listSubtitles as ytdlpList, downloadSubtitle as ytdlpDownload } from "./ytdlp";
import { getYoutubeVideoInfo, getYoutubeCaptions } from "./api";
import { fetchTimedText } from "@/lib/platform/youtube";
import { listSubtitlesViaBrowser, downloadSubtitleViaBrowser } from "./browser";
import { getCachedSubtitle, setCachedSubtitle } from "./cache";
import { getVideoInfo, cacheVideoInfo } from "@/lib/video/info";
import { validateAndParseUrl } from "@/lib/video/validator";
import { getProxy, buildProxyUrl } from "@/lib/anti-limit/rotator";
import type { AnalyzeResponse } from "@/types/video";

export async function analyzeVideo(url: string): Promise<AnalyzeResponse> {
  // Step 0: Validate URL
  const validation = validateAndParseUrl(url);
  if (!validation.isValid) {
    return {
      success: false,
      ccSubtitles: [],
      autoTranslated: [],
      hasVoice: true,
      error: "invalid_url",
      message: "您请求的视频不存在，请检查视频链接是否正确",
    };
  }

  const { platform, videoId, sanitizedUrl } = validation;

  // Step 1: Check cache for video info
  let videoInfo;
  const cachedInfo = await getVideoInfo(videoId!, platform!, sanitizedUrl);
  if (cachedInfo) {
    videoInfo = cachedInfo;
  }

  // Step 2: Try yt-dlp (primary method)
  let ccSubtitles: SubtitleTrack[] = [];
  let autoTranslated: SubtitleTrack[] = [];

  // Acquire a proxy for the request
  const proxy = await getProxy("random");
  const proxyUrl = proxy ? buildProxyUrl(proxy) : undefined;

  const ytOptions = { platform: platform!, proxy: proxyUrl };

  const ytdlpResult = await ytdlpList(sanitizedUrl, ytOptions);
  if (ytdlpResult.videoInfo) {
    videoInfo = {
      videoId: videoId!,
      platform: platform!,
      ...ytdlpResult.videoInfo,
    };
    cacheVideoInfo(videoInfo).catch(() => {});
  }
  ccSubtitles = ytdlpResult.ccSubtitles;
  autoTranslated = ytdlpResult.autoTranslated;

  // Step 3a: Try YouTube Data API v3 (fallback if no subtitles from yt-dlp)
  if (ccSubtitles.length === 0 && autoTranslated.length === 0 && platform === "youtube") {
    const apiResult = await getYoutubeCaptions(videoId!);
    ccSubtitles = apiResult.ccSubtitles;
    autoTranslated = apiResult.autoTranslated;

    if (!videoInfo) {
      const ytInfo = await getYoutubeVideoInfo(videoId!);
      if (ytInfo) {
        videoInfo = {
          videoId: videoId!,
          platform: "youtube",
          ...ytInfo,
        };
        cacheVideoInfo(videoInfo).catch(() => {});
      }
    }
  }

  // Step 3b: Try YouTube timedtext API (another fallback for YouTube)
  if (ccSubtitles.length === 0 && autoTranslated.length === 0 && platform === "youtube" && videoId) {
    try {
      const timedText = await fetchTimedText(videoId, "en");
      if (timedText && timedText.length > 100) {
        // If we got content, at least English auto-captions are available
        autoTranslated.push({
          langCode: "en",
          langName: "English (自动)",
          isAutoGenerated: true,
          isTranslation: false,
        });
      }
    } catch {
      // quiet fallback
    }
  }

  // Step 4: Try browser simulation (last resort)
  if (ccSubtitles.length === 0 && autoTranslated.length === 0) {
    const browserResult = await listSubtitlesViaBrowser(sanitizedUrl);
    ccSubtitles = browserResult.ccSubtitles;
    autoTranslated = browserResult.autoTranslated;
    if (browserResult.videoInfo && !videoInfo) {
      videoInfo = {
        videoId: videoId!,
        platform: platform!,
        ...browserResult.videoInfo,
      };
      cacheVideoInfo(videoInfo).catch(() => {});
    }
  }

  // Deduplicate: remove any autoTranslated that also appear in ccSubtitles
  const ccLangSet = new Set(ccSubtitles.map((s) => s.langCode));
  autoTranslated = autoTranslated.filter((s) => !ccLangSet.has(s.langCode));

  const hasAnySubtitles = ccSubtitles.length > 0 || autoTranslated.length > 0;

  return {
    success: true,
    videoInfo: videoInfo || undefined,
    ccSubtitles,
    autoTranslated,
    hasVoice: hasAnySubtitles,
    message: hasAnySubtitles
      ? undefined
      : "该视频未检测到任何字幕文件，无法下载",
  };
}

export async function downloadSubtitle(
  videoUrl: string,
  langCode: string,
  format: SubtitleFormat,
  subtitleType: string = "cc"
): Promise<{ content: string | null; cached: boolean }> {
  const validation = validateAndParseUrl(videoUrl);
  if (!validation.isValid || !validation.videoId) {
    return { content: null, cached: false };
  }

  const { videoId, platform, sanitizedUrl } = validation;

  // Step 1: Check cache
  const cached = await getCachedSubtitle(
    videoId!,
    platform!,
    langCode,
    subtitleType,
    format
  );
  if (cached) {
    return { content: cached, cached: true };
  }

  // Step 2: Try yt-dlp download (with proxy and cookies)
  const proxy = await getProxy("random");
  const proxyUrl = proxy ? buildProxyUrl(proxy) : undefined;

  let content = await ytdlpDownload(sanitizedUrl, langCode, format, {
    platform: platform!,
    proxy: proxyUrl,
    videoId: videoId!,
    subtitleType,
  });

  // Step 2b: Cross-try the other subtitle type(s).
  // translated → auto-generated (try ASR in same language)
  // auto-generated → cc        (try manual CC)
  // cc              → auto-generated (try ASR)
  if (!content) {
    let altType: string;
    if (subtitleType === "auto-generated") {
      altType = "cc";
    } else if (subtitleType === "translated") {
      altType = "auto-generated";
    } else {
      altType = "auto-generated";
    }
    content = await ytdlpDownload(sanitizedUrl, langCode, format, {
      platform: platform!,
      proxy: proxyUrl,
      videoId: videoId!,
      subtitleType: altType,
    });

    // If translated → auto also failed, try manual CC as last resort
    if (!content && subtitleType === "translated") {
      content = await ytdlpDownload(sanitizedUrl, langCode, format, {
        platform: platform!,
        proxy: proxyUrl,
        videoId: videoId!,
        subtitleType: "cc",
      });
    }
  }

  // Step 3: For YouTube, try yt-dlp with extractor args as fallback
  // (the fast path above skips player_client to avoid PO token issues)
  if (!content && platform === "youtube" && videoId) {
    // Try timedtext API with the URL from yt-dlp's listing output
    const timedText = await fetchTimedText(videoId, langCode, {
      format: format === "srt" ? "srt" : "vtt",
    });
    if (timedText && timedText.length > 100) {
      content = timedText;
    }
  }

  // Step 4: Try browser download (last resort)
  if (!content) {
    content = await downloadSubtitleViaBrowser(sanitizedUrl, langCode, format);
  }

  // Step 5: Cache the result
  if (content) {
    await setCachedSubtitle(
      videoId!,
      platform!,
      sanitizedUrl,
      langCode,
      subtitleType,
      format,
      content
    );
  }

  return { content, cached: false };
}
