import { execFile } from "child_process";
import { promisify } from "util";
import path from "path";
import os from "os";
import fs from "fs/promises";
import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";
import { convertSubtitle, detectFormat } from "./converter";
import { createTempCookieFile, cleanupTempCookieFile } from "./cookies-file";

const execFileAsync = promisify(execFile);
const YTDLP_PATH = "yt-dlp";

const SAFE_LANG_PATTERN = /^[a-zA-Z0-9_-]+$/;

function isSafeArg(value: string): boolean {
  return SAFE_LANG_PATTERN.test(value);
}

interface YtDlpOptions {
  /** Proxy URL (e.g. http://user:pass@host:port) */
  proxy?: string;
  /** Platform name for cookie lookup */
  platform?: string;
  /** External cookie file path (takes precedence over platform lookup) */
  cookieFile?: string;
  /** Known video ID (avoids redundant --dump-json call) */
  videoId?: string;
  /** Subtitle type: "cc" (manual) or "auto-generated" */
  subtitleType?: string;
}

interface YtDlpSubtitle {
  lang: string;
  name: string;
  url?: string;
  ext?: string;
}

interface YtDlpVideoInfo {
  id: string;
  title: string;
  description?: string;
  duration?: number;
  thumbnail?: string;
  upload_date?: string;
  uploader?: string;
  channel?: string;
  subtitles: Record<string, YtDlpSubtitle[]>;
  automatic_captions: Record<string, YtDlpSubtitle[]>;
}

const BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";

function buildBaseArgs(url: string): string[] {
  return [
    "--no-playlist",
    "--socket-timeout", "45",
    "--retries", "5",
    "--fragment-retries", "5",
    "--extractor-retries", "3",
    url,
  ];
}

function buildAntiLimitArgs(): string[] {
  return [
    "--sleep-requests", "1",
    "--sleep-interval", "5",
    "--max-sleep-interval", "15",
    "--user-agent", BROWSER_UA,
  ];
}

/**
 * Lightweight args for subtitle-only downloads — skips the sleep intervals
 * that can push download time past the 60s timeout when combined with
 * retries and multiple player client fallbacks.
 */
function buildDownloadArgs(url: string): string[] {
  return [
    "--no-playlist",
    "--socket-timeout", "30",
    "--retries", "3",
    "--extractor-retries", "2",
    "--user-agent", BROWSER_UA,
    url,
  ];
}

/**
 * Acquire a cookie file for the platform. Tries the explicit cookieFile option
 * first, then falls back to the database-managed cookies.
 */
async function resolveCookieFile(
  options?: YtDlpOptions
): Promise<{ filePath: string | null; needsCleanup: boolean }> {
  if (options?.cookieFile) {
    return { filePath: options.cookieFile, needsCleanup: false };
  }
  if (options?.platform) {
    const tmp = await createTempCookieFile(options.platform);
    return { filePath: tmp, needsCleanup: true };
  }
  return { filePath: null, needsCleanup: false };
}

export async function listSubtitles(
  url: string,
  options?: YtDlpOptions
): Promise<{
  ccSubtitles: SubtitleTrack[];
  autoTranslated: SubtitleTrack[];
  videoInfo: {
    title: string;
    author: string;
    duration?: number;
    thumbnail?: string;
    uploadDate?: string;
    description?: string;
  } | null;
}> {
  const { filePath: cookieFile, needsCleanup } = await resolveCookieFile(options);

  try {
    // --write-auto-subs + --write-subs tell yt-dlp to populate the full
    // automatic_captions dict including all translation languages (e.g.
    // fr-zh = French from Chinese). Without these flags only the base
    // ASR tracks (zh, en) are returned. --dump-json still prevents any
    // actual download.
    const args: string[] = [
      "--dump-json",
      "--write-auto-subs",
      "--write-subs",
      ...buildBaseArgs(url),
      ...buildAntiLimitArgs(),
    ];

    if (cookieFile) args.push("--cookies", cookieFile);
    if (options?.proxy) args.push("--proxy", options.proxy);

    const { stdout } = await execFileAsync(YTDLP_PATH, args, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 60000,
    });

    const info: YtDlpVideoInfo = JSON.parse(stdout);

    const ccSubtitles: SubtitleTrack[] = [];
    const autoTranslated: SubtitleTrack[] = [];

    if (info.subtitles) {
      for (const [langCode, subs] of Object.entries(info.subtitles)) {
        if (subs.length > 0) {
          ccSubtitles.push({
            langCode,
            langName: subs[0].name || langCode,
            url: subs[0].url,
            isAutoGenerated: false,
            isTranslation: false,
          });
        }
      }
    }

    if (info.automatic_captions) {
      // First pass: identify base ASR tracks (non-translated)
      const baseAsrCodes = new Set<string>();
      for (const [langCode, subs] of Object.entries(info.automatic_captions)) {
        if (subs.length === 0) continue;
        const name = subs[0].name || "";
        if (!/\bfrom\b/i.test(name)) {
          baseAsrCodes.add(langCode);
        }
      }

      // Target languages worth showing (ISO 639-1 codes of widely spoken languages)
      const PREFERRED_TARGETS = new Set([
        "en", "zh", "zh-Hans", "zh-Hant", "ja", "ko", "es", "fr", "de",
        "pt", "ru", "ar", "hi", "th", "vi", "id", "it", "tr", "nl",
        "pl", "uk", "bn", "ms", "sv", "no", "da", "fi", "cs", "hu",
        "ro", "he", "el", "ta", "te", "fa", "fil", "iw", "sk", "bg",
        "hr", "sr", "sl", "lt", "lv", "et", "sw", "ur",
      ]);

      for (const [langCode, subs] of Object.entries(info.automatic_captions)) {
        if (subs.length === 0) continue;
        if (ccSubtitles.find((s) => s.langCode === langCode)) continue;

        const name = subs[0].name || "";
        const isTranslation = /\bfrom\b/i.test(name);

        // For translated tracks, only include those whose target language
        // is in the preferred set (avoids 300+ obscure translations).
        if (isTranslation) {
          let targetCode = "";
          for (const base of baseAsrCodes) {
            const suffix = `-${base}`;
            if (langCode.endsWith(suffix) && langCode !== base) {
              targetCode = langCode.slice(0, -suffix.length);
              break;
            }
          }
          // If we can't determine the target, default to showing it
          if (targetCode && !PREFERRED_TARGETS.has(targetCode)) continue;
        }

        autoTranslated.push({
          langCode,
          langName: isTranslation ? name : `${name || langCode} (自动)`,
          url: subs[0].url,
          isAutoGenerated: true,
          isTranslation,
        });
      }
    }

    const videoInfo = {
      title: info.title || "Unknown",
      author: info.uploader || info.channel || "Unknown",
      duration: info.duration,
      thumbnail: info.thumbnail,
      uploadDate: info.upload_date,
      description: info.description,
    };

    return { ccSubtitles, autoTranslated, videoInfo };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp listSubtitles error:", errorMsg);
    return { ccSubtitles: [], autoTranslated: [], videoInfo: null };
  } finally {
    if (needsCleanup && cookieFile) {
      cleanupTempCookieFile(cookieFile).catch(() => {});
    }
  }
}

export async function downloadSubtitle(
  url: string,
  langCode: string,
  targetFormat: SubtitleFormat,
  options?: YtDlpOptions
): Promise<string | null> {
  if (!isSafeArg(langCode)) return null;

  // Use OS temp directory (guaranteed writable) rather than app data dir
  // which may be a Docker volume mount with wrong permissions.
  const tmpDir = path.join(os.tmpdir(), "mlangsub", String(Date.now()));
  await fs.mkdir(tmpDir, { recursive: true });

  const { filePath: cookieFile, needsCleanup } = await resolveCookieFile(options);

  const isAutoGenerated = options?.subtitleType === "auto-generated";

  try {
    // Fast path: no sleep delays for subtitle-only downloads
    const args: string[] = [
      isAutoGenerated ? "--write-auto-subs" : "--write-subs",
      "--sub-lang", langCode,
      "--skip-download",
      "-o", path.join(tmpDir, "%(id)s.%(ext)s"),
      ...buildDownloadArgs(url),
    ];

    // Auto-generated captions require the Android player client on newer
    // yt-dlp versions — the web client needs a PO token for timedtext API
    // access and will return "no subtitles" without one.
    if (isAutoGenerated) {
      args.push("--extractor-args", "youtube:player_client=android");
    }

    if (cookieFile) args.push("--cookies", cookieFile);
    if (options?.proxy) args.push("--proxy", options.proxy);

    await execFileAsync(YTDLP_PATH, args, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 90000,
    });

    // Use provided videoId or fetch it via --dump-json
    let videoId = options?.videoId;
    if (!videoId) {
      const infoArgs: string[] = [
        "--dump-json",
        ...buildDownloadArgs(url),
      ];
      if (cookieFile) infoArgs.push("--cookies", cookieFile);
      if (options?.proxy) infoArgs.push("--proxy", options.proxy);

      const { stdout: infoStdout } = await execFileAsync(YTDLP_PATH, infoArgs, {
        maxBuffer: 10 * 1024 * 1024,
        timeout: 60000,
      });
      const info = JSON.parse(infoStdout);
      videoId = info.id;
    }

    // Find any subtitle file matching this video ID
    let files: string[] = [];
    try {
      files = await fs.readdir(tmpDir);
    } catch {
      return null;
    }

    const matchingFiles = files.filter((f) => f.startsWith(videoId!));

    if (matchingFiles.length === 0) return null;

    // Prefer file with matching language code, otherwise use first match
    const bestMatch =
      matchingFiles.find((f) => f.includes(langCode)) || matchingFiles[0];

    const filePath = path.join(tmpDir, bestMatch);
    const rawContent = await fs.readFile(filePath, "utf-8");
    const sourceFormat = detectFormat(rawContent);

    if (sourceFormat === targetFormat) return rawContent;
    return convertSubtitle(rawContent, sourceFormat, targetFormat);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp downloadSubtitle error:", errorMsg);
    return null;
  } finally {
    if (needsCleanup && cookieFile) {
      cleanupTempCookieFile(cookieFile).catch(() => {});
    }
    // Clean up temp directory
    fs.rm(tmpDir, { recursive: true, force: true }).catch(() => {});
  }
}
