import { execFile } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs/promises";
import type { SubtitleTrack, SubtitleFormat } from "@/types/subtitle";
import { convertSubtitle, detectFormat } from "./converter";
import { createTempCookieFile, cleanupTempCookieFile } from "./cookies-file";

const execFileAsync = promisify(execFile);
const YTDLP_PATH = "yt-dlp";

const SAFE_LANG_PATTERN = /^[a-zA-Z0-9_-]+$/;

function isSafeArg(value: string): boolean {
  return SAFE_LANG_PATTERN.test(value);
}

interface YtDlpOptions {
  /** Proxy URL (e.g. http://user:pass@host:port) */
  proxy?: string;
  /** Platform name for cookie lookup */
  platform?: string;
  /** External cookie file path (takes precedence over platform lookup) */
  cookieFile?: string;
  /** Known video ID (avoids redundant --dump-json call) */
  videoId?: string;
  /** Subtitle type: "cc" (manual) or "auto-generated" */
  subtitleType?: string;
}

interface YtDlpSubtitle {
  lang: string;
  name: string;
  url?: string;
  ext?: string;
}

interface YtDlpVideoInfo {
  id: string;
  title: string;
  description?: string;
  duration?: number;
  thumbnail?: string;
  upload_date?: string;
  uploader?: string;
  channel?: string;
  subtitles: Record<string, YtDlpSubtitle[]>;
  automatic_captions: Record<string, YtDlpSubtitle[]>;
}

const BROWSER_UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";

function buildBaseArgs(url: string): string[] {
  return [
    "--no-playlist",
    "--socket-timeout", "45",
    "--retries", "5",
    "--fragment-retries", "5",
    "--extractor-retries", "3",
    url,
  ];
}

function buildYoutubeExtractorArgs(): string[] {
  return [
    "--extractor-args", "youtube:player_client=android,ios,web",
  ];
}

function buildAntiLimitArgs(): string[] {
  return [
    "--sleep-requests", "1",
    "--sleep-interval", "5",
    "--max-sleep-interval", "15",
    "--user-agent", BROWSER_UA,
  ];
}

/**
 * Acquire a cookie file for the platform. Tries the explicit cookieFile option
 * first, then falls back to the database-managed cookies.
 */
async function resolveCookieFile(
  options?: YtDlpOptions
): Promise<{ filePath: string | null; needsCleanup: boolean }> {
  if (options?.cookieFile) {
    return { filePath: options.cookieFile, needsCleanup: false };
  }
  if (options?.platform) {
    const tmp = await createTempCookieFile(options.platform);
    return { filePath: tmp, needsCleanup: true };
  }
  return { filePath: null, needsCleanup: false };
}

export async function listSubtitles(
  url: string,
  options?: YtDlpOptions
): Promise<{
  ccSubtitles: SubtitleTrack[];
  autoTranslated: SubtitleTrack[];
  videoInfo: {
    title: string;
    author: string;
    duration?: number;
    thumbnail?: string;
    uploadDate?: string;
    description?: string;
  } | null;
}> {
  const { filePath: cookieFile, needsCleanup } = await resolveCookieFile(options);

  try {
    // Use default web client for listing — returns the most complete subtitle
    // metadata (including automatic_captions) that android/ios clients may omit.
    const args: string[] = [
      "--dump-json",
      ...buildBaseArgs(url),
      ...buildAntiLimitArgs(),
    ];

    if (cookieFile) args.push("--cookies", cookieFile);
    if (options?.proxy) args.push("--proxy", options.proxy);

    const { stdout } = await execFileAsync(YTDLP_PATH, args, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 60000,
    });

    const info: YtDlpVideoInfo = JSON.parse(stdout);

    const ccSubtitles: SubtitleTrack[] = [];
    const autoTranslated: SubtitleTrack[] = [];

    if (info.subtitles) {
      for (const [langCode, subs] of Object.entries(info.subtitles)) {
        if (subs.length > 0) {
          ccSubtitles.push({
            langCode,
            langName: subs[0].name || langCode,
            url: subs[0].url,
            isAutoGenerated: false,
            isTranslation: false,
          });
        }
      }
    }

    if (info.automatic_captions) {
      for (const [langCode, subs] of Object.entries(info.automatic_captions)) {
        if (subs.length > 0) {
          if (ccSubtitles.find((s) => s.langCode === langCode)) continue;

          autoTranslated.push({
            langCode,
            langName: `${subs[0].name || langCode} (自动)`,
            url: subs[0].url,
            isAutoGenerated: true,
            isTranslation:
              langCode !== "en" && langCode !== "zh-Hans" && langCode !== "zh-Hant",
          });
        }
      }
    }

    const videoInfo = {
      title: info.title || "Unknown",
      author: info.uploader || info.channel || "Unknown",
      duration: info.duration,
      thumbnail: info.thumbnail,
      uploadDate: info.upload_date,
      description: info.description,
    };

    return { ccSubtitles, autoTranslated, videoInfo };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp listSubtitles error:", errorMsg);
    return { ccSubtitles: [], autoTranslated: [], videoInfo: null };
  } finally {
    if (needsCleanup && cookieFile) {
      cleanupTempCookieFile(cookieFile).catch(() => {});
    }
  }
}

export async function downloadSubtitle(
  url: string,
  langCode: string,
  targetFormat: SubtitleFormat,
  options?: YtDlpOptions
): Promise<string | null> {
  if (!isSafeArg(langCode)) return null;

  const tmpDir = path.join(process.cwd(), "data", "tmp");
  await fs.mkdir(tmpDir, { recursive: true });

  const { filePath: cookieFile, needsCleanup } = await resolveCookieFile(options);

  // Use --write-auto-subs for auto-generated captions, --write-subs for manual CC
  const isAutoGenerated = options?.subtitleType === "auto-generated";

  try {
    const args: string[] = [
      isAutoGenerated ? "--write-auto-subs" : "--write-subs",
      "--sub-lang", langCode,
      "--skip-download",
      "-o", path.join(tmpDir, "%(id)s.%(ext)s"),
      ...buildBaseArgs(url),
      ...buildYoutubeExtractorArgs(),
      ...buildAntiLimitArgs(),
    ];

    if (cookieFile) args.push("--cookies", cookieFile);
    if (options?.proxy) args.push("--proxy", options.proxy);

    await execFileAsync(YTDLP_PATH, args, {
      maxBuffer: 10 * 1024 * 1024,
      timeout: 60000,
    });

    // Use provided videoId or fetch it via --dump-json
    let videoId = options?.videoId;
    if (!videoId) {
      const infoArgs: string[] = [
        "--dump-json",
        ...buildBaseArgs(url),
        ...buildYoutubeExtractorArgs(),
        ...buildAntiLimitArgs(),
      ];
      if (cookieFile) infoArgs.push("--cookies", cookieFile);
      if (options?.proxy) infoArgs.push("--proxy", options.proxy);

      const { stdout: infoStdout } = await execFileAsync(YTDLP_PATH, infoArgs, {
        maxBuffer: 10 * 1024 * 1024,
        timeout: 60000,
      });
      const info = JSON.parse(infoStdout);
      videoId = info.id;
    }

    // Find any subtitle file matching this video ID
    const files = await fs.readdir(tmpDir);
    const matchingFiles = files.filter((f) => f.startsWith(videoId!));

    if (matchingFiles.length === 0) return null;

    // Prefer file with matching language code, otherwise use first match
    const bestMatch =
      matchingFiles.find((f) => f.includes(langCode)) || matchingFiles[0];

    const filePath = path.join(tmpDir, bestMatch);
    const rawContent = await fs.readFile(filePath, "utf-8");
    const sourceFormat = detectFormat(rawContent);

    if (sourceFormat === targetFormat) return rawContent;
    return convertSubtitle(rawContent, sourceFormat, targetFormat);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.error("yt-dlp downloadSubtitle error:", errorMsg);
    return null;
  } finally {
    if (needsCleanup && cookieFile) {
      cleanupTempCookieFile(cookieFile).catch(() => {});
    }
  }
}
